##
## Author:   liyuqihxc
## License:  See LICENSE file included in the project
##
##
## stm32 cubemx configuration CMake file
##

# All relative to project root, as generated by STM32CubeMX.
set(CORE_DIR ${CMAKE_SOURCE_DIR}/Generated/Core)
set(CMSIS_DIR ${CMAKE_SOURCE_DIR}/Generated/Drivers/CMSIS)
set(DEVICE_DIR ${CMAKE_SOURCE_DIR}/Generated/Drivers/CMSIS/Device/ST/STM32F1xx)

# Some trickery to get CMake to deal with our assembler code.
set_property(SOURCE ${STARTUP_ASSEMBLY} PROPERTY LANGUAGE C)
