##
## Author:   liyuqihxc
## License:  See LICENSE file included in the project
##
##
## stm32 cubemx configuration CMake file
##

# All relative to project root, as generated by STM32CubeMX.
set(CORE_DIR ${CMAKE_SOURCE_DIR}/Core)
set(CMSIS_DIR ${CMAKE_SOURCE_DIR}/Drivers/CMSIS)

# Look here for header files.
include_directories(${CORE_DIR}/Inc)
include_directories(${CMSIS_DIR}/Include)

# add_library(cubemx INTERFACE)
# target_compile_definitions(cubemx INTERFACE -D${MCU_FAMILY})
# target_include_directories(cubemx INTERFACE
#   $<BUILD_INTERFACE:${CORE_DIR}/Include>
#   $<BUILD_INTERFACE:${DEVICE_DIR}/Include>)

# Some trickery to get CMake to deal with our assembler code.
set_property(SOURCE ${STARTUP_ASSEMBLY} PROPERTY LANGUAGE C)
