##
## Author:   liyuqihxc
## License:  See LICENSE file included in the project
##
##
## stm32f103 target specific CMake file
##

if(NOT DEFINED MCU_LINKER_SCRIPT)
    message(FATAL_ERROR "No linker script defined")
endif(NOT DEFINED MCU_LINKER_SCRIPT)
message("Linker script: ${MCU_LINKER_SCRIPT}")

# Generated by STM32CubeMX.
set(HAL_DIR ${CMAKE_SOURCE_DIR}/Generated/Drivers/STM32F1xx_HAL_Driver)

# Compile and link
set(MCU_FLAGS "-mcpu=cortex-m3 -mthumb ${FPU} ${FLOAT-ABI}")
set(COMMON_FLAGS "${MCU_FLAGS} -DUSE_HAL_DRIVER -D${MCU_LINE}")

set(CMAKE_C_FLAGS "${COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS "${COMMON_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${MCU_FLAGS} --specs=nosys.specs -T \"${CMAKE_SOURCE_DIR}/${MCU_LINKER_SCRIPT}\" -Wl,--cref")

# The linker flag --gc-section keeps unused object code here from being linked.
